name: fenix_mobile
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  go_router: ^15.1.1
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.4




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0

flutter_native_splash:
 android: true
 ios: true
 web: false 

 color: "#ffffff"
 background_image: "assets/images/logo.png"

 android_12:
  color: "#ffffff"
  background_image: "assets/images/logo.png"

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icon/